version: "3"
services: 
  api-gateway:
    build:
      context: "."
      dockerfile: "./api-gateway/Dockerfile"
    depends_on: 
      - chat-service
      - users-service
    ports:
      - "7001:7001"
    volumes:
      - ./api-gateway:/opt/app

  chat-service:
    build:
      context: "."
      dockerfile: "./chat-service/Dockerfile"
    depends_on: 
      - chat-service-db
    ports:
      - "7100:7100"
    volumes:
      - ./chat-service:/opt/app 
  
  chat-service-db:
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: password
    platform: linux/x86_64
    image: mysql:8.0.26
    ports:
      - "7200:3306"
  
  phpmyadmin:
    environment: 
      PMA_HOSTS: chat-service-db,users-service-db
    image: phpmyadmin/phpmyadmin
    ports: 
      - "7300:80"
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
  
  users-service:
    build:
      context: "."
      dockerfile: "./users-service/Dockerfile"
    depends_on: 
      - users-service-db
    ports:
      - "7101:7101"
    volumes:
      - ./users-service:/opt/app
  
  users-service-db:
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: password
    image: mysql:8.0.26
    platform: linux/x86_64
    ports:
      - "7201:3306"